#!/bin/zsh


echo "\ninitializing the database..."
psql -U postgres -d disc -b -w -f ./ddl.dump.sql > /dev/null

echo "generating person and email db records..."
node genPersonEmail.mjs 

echo "generating notification setting db records..."
node notificationSettings.mjs

# uncomment below 2 lines if first time running on a particular machine
#echo "generating sql scripts for course and term record gen..."
#python3 genCourseTermSqlScript.py

echo "generating term db records..."
psql -U postgres -d disc -b -w -f ./dml.sample.term.sql > /dev/null # generated by python script

echo "generating course db records..."
psql -U postgres -d disc -b -w -f ./dml.sample.course.sql > /dev/null # generated by python script

echo "generating course enrollment records..."
node enroll.mjs

echo "generating post category records..."
node postCategory.mjs

echo "generating ~100k post records... this should take about a minute"
node posts.mjs

echo "generating ~200k comment records... this will take a few minutes"
node comment.mjs